"""Feature 10.3 — deterministic whole-workflow diagram generation (Mermaid).

`generate_diagrams(db)` emits a `DIAGRAMS.md` of fenced ```mermaid blocks
*mechanically* from Sylva's analysis — the system flow (9.4, rooted at the
inferred primary, main spine styled), the package module map (4.7), and the
architectural-layer tiers (9.8). GitHub renders the blocks; an agent can annotate
them with meaning afterwards (the optional skill wrapper).

Deterministic and reproducible; Sylva runs no LLM here. Test code is filtered so
the diagrams describe the system, not the suite (reuses 10.1's `_is_test_file`).
"""

import os
from collections import Counter

import sylva
from . import viz
from .report import _is_test_file


def _san(s):
    """Sanitise a Mermaid node label."""
    return str(s).replace('"', "'").replace("\n", " ").replace("\\", "/")


def _system_flow_block(db_path):
    sf = viz.system_flow(db_path)
    lines = ["```mermaid", "flowchart TD"]
    if not sf.get("nodes"):
        lines += ["  empty[\"(no entrypoint / empty graph)\"]", "```"]
        return "\n".join(lines)
    spine = False
    for n in sf["nodes"]:
        cls = ""
        if n.get("on_spine"):
            cls, spine = ":::spine", True
        lines.append(f'  n{n["id"]}["{_san(n["name"])}"]{cls}')
    for e in sf["edges"]:
        lines.append(f'  n{e["source"]} --> n{e["target"]}')
    if spine:
        lines.append("classDef spine fill:#a371f7,stroke:#ffffff,color:#ffffff;")
    lines.append("```")
    return "\n".join(lines)


def _module_map_block(db_path):
    mm = viz.module_map(db_path, "package")
    nodes = [n for n in mm["nodes"] if not _is_test_file(n["id"])]
    ids = {n["id"]: f"m{i}" for i, n in enumerate(nodes)}
    lines = ["```mermaid", "flowchart LR"]
    if not nodes:
        lines += ['  empty["(no modules)"]', "```"]
        return "\n".join(lines)
    for n in nodes:
        lines.append(f'  {ids[n["id"]]}["{_san(n["label"])} ({n["symbols"]})"]')
    for e in mm["edges"]:
        if e["source"] in ids and e["target"] in ids:
            lines.append(f'  {ids[e["source"]]} -->|{e["weight"]}| {ids[e["target"]]}')
    lines.append("```")
    return "\n".join(lines)


def _layer_block(db_path):
    layers = sylva.infer_layers(db_path)
    if layers["archetype"] == "library":
        return None  # no tier decomposition for libraries
    counts = Counter(e["layer"] for e in layers["layers"] if not _is_test_file(e["file"]))
    if not counts:
        return None
    lines = ["```mermaid", "flowchart TD"]
    for tier in ("interface", "business", "data", "transport"):
        if counts.get(tier):
            lines.append(f'  {tier}["{tier} ({counts[tier]})"]')
    present = [t for t in ("interface", "business", "data") if counts.get(t)]
    for a, b in zip(present, present[1:]):
        lines.append(f"  {a} --> {b}")
    if counts.get("transport") and counts.get("business"):
        lines.append("  business --> transport")
    lines.append("```")
    return "\n".join(lines)


def generate_diagrams(db_path):
    """Return a markdown document of Mermaid diagrams for the graph at `db_path`.

    Raises FileNotFoundError if the database does not exist.
    """
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"database not found: {db_path}")

    out = [
        "# Project Diagrams",
        "",
        "> Auto-generated by Sylva from the code graph (deterministic — regenerate "
        "with `sylva diagram`). GitHub renders the Mermaid blocks below.",
        "",
        "## System flow",
        "",
        "The reachable call flow from the inferred primary entrypoint; the main "
        "execution spine is highlighted.",
        "",
        _system_flow_block(db_path),
        "",
        "## Module map (packages)",
        "",
        "Package-level dependencies; edge labels are the number of cross-package "
        "call/import relationships.",
        "",
        _module_map_block(db_path),
        "",
    ]
    layer = _layer_block(db_path)
    if layer:
        out += [
            "## Architectural layers",
            "",
            "Symbol counts per architectural tier.",
            "",
            layer,
            "",
        ]
    out += ["---", "_Generated by Sylva. Re-run `sylva diagram` after re-indexing._", ""]
    return "\n".join(out)
