"""Feature 8.5 — expose selected repo functions as an executable MCP server.

Given a **language-neutral allowlist** (`.codemcp/expose.toml`), generate a
**standalone, dependency-free** MCP server that exposes *only* the listed
functions as callable tools. This is interpretation (B) from #41: an agent can
*invoke* the repo's own code, not just query the graph.

Safety: Sylva **generates**; the user **reviews and runs** the server in their
own environment — Sylva executes nothing here. Nothing is exposed unless it is
explicitly allowlisted. Python execution backend first (import + live
`inspect.signature`); the allowlist format names any language so other backends
can be added without changing the selection contract.
"""

import os
import re
import sqlite3


def parse_allowlist(text):
    """Parse the allowlist. TOML-ish `functions = [...]` / `modules = [...]`
    arrays of strings — extracted with a dependency-free scan (works on any
    Python version). Returns `{"functions": [...], "modules": [...]}`."""

    def arr(key):
        m = re.search(key + r"\s*=\s*\[(.*?)\]", text, re.S)
        return re.findall(r"""["']([^"']+)["']""", m.group(1)) if m else []

    return {"functions": arr("functions"), "modules": arr("modules")}


def _module_from_path(path, root):
    """Dotted import path of a file relative to `root` (`pkg/mod.py` → `pkg.mod`,
    a package `__init__.py` → the package)."""
    rel = os.path.relpath(path, root).replace("\\", "/")
    if rel.endswith(".py"):
        rel = rel[:-3]
    parts = [p for p in rel.split("/") if p and p != "."]
    if parts and parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def _file_matches_module(path, module):
    """Does `path` correspond to the dotted `module`? (`pkg.mod` ↔ `.../pkg/mod.py`)."""
    stripped = path[:-3] if path.endswith(".py") else path
    comps = [c for c in stripped.replace("\\", "/").split("/") if c and c != "."]
    if comps and comps[-1] == "__init__":
        comps = comps[:-1]
    mod = [c for c in module.split(".") if c]
    return bool(mod) and len(comps) >= len(mod) and comps[-len(mod):] == mod


def _resolve(db_path, root, allowlist):
    """Resolve the allowlist against the graph → `([(module, fn, desc)], warnings)`."""
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT s.name, s.kind, f.path, s.line_start, s.line_end, s.docstring "
            "FROM symbols s JOIN files f ON f.id = s.file_id"
        ).fetchall()
    finally:
        conn.close()

    funcs = [(n, p, ls, le, doc) for (n, k, p, ls, le, doc) in rows if k == "function"]
    class_spans = [(p, ls, le) for (n, k, p, ls, le, doc) in rows if k == "class"]

    def desc_of(doc, module, fn):
        first = (doc or "").strip().splitlines()
        return first[0] if first else f"{module}.{fn}"

    def is_method(path, ls, le):
        return any(
            cp == path and cls is not None and cle is not None and cls <= (ls or 0) and (le or 0) <= cle
            for (cp, cls, cle) in class_spans
        )

    targets, warnings = [], []

    for spec in allowlist.get("functions", []):
        mod = None
        if ":" in spec:
            mod, fn = spec.split(":", 1)
            matches = [r for r in funcs if r[0] == fn and _file_matches_module(r[1], mod)]
        else:
            fn = spec
            matches = [r for r in funcs if r[0] == fn]
        if not matches:
            warnings.append(f"'{spec}' not found in the graph; skipped")
            continue
        if len(matches) > 1 and mod is None:
            warnings.append(f"'{spec}' is ambiguous ({len(matches)} matches); qualify as module:function")
            continue
        n, p, ls, le, doc = matches[0]
        module = mod or _module_from_path(p, root)
        targets.append((module, fn, desc_of(doc, module, fn)))

    for mod in allowlist.get("modules", []):
        in_mod = [r for r in funcs if _file_matches_module(r[1], mod)]
        if not in_mod:
            warnings.append(f"module '{mod}' has no functions in the graph; skipped")
            continue
        for n, p, ls, le, doc in in_mod:
            if n.startswith("_") or is_method(p, ls, le):
                continue  # skip privates and methods (module shorthand = public fns)
            targets.append((mod, n, desc_of(doc, mod, n)))

    return targets, warnings


# The runtime server logic — static, dependency-free. Token placeholders are
# substituted (not str.format) to avoid escaping the braces in generated code.
_SERVER_TEMPLATE = '''#!/usr/bin/env python3
"""GENERATED BY SYLVA — do not edit by hand (regenerate with `sylva expose`).

Exposes selected functions of this project as MCP tools an agent can CALL.

  !! TRUST BOUNDARY !!
  Running this server lets a connected MCP client EXECUTE the functions below
  in this environment. Only the explicitly allowlisted functions are exposed.
  Review this file before running it.

Exposed surface:
__SYLVA_SURFACE__
"""
import inspect
import json
import os
import sys

# The project root, so the exposed modules below import regardless of cwd.
sys.path.insert(0, __SYLVA_ROOT__)

__SYLVA_IMPORTS__

TOOLS = {
__SYLVA_REGISTRATIONS__
}


def _json_type(annotation):
    return {int: "integer", float: "number", bool: "boolean", str: "string"}.get(annotation, "string")


def _schema(fn):
    props, required = {}, []
    try:
        sig = inspect.signature(fn)
    except (ValueError, TypeError):
        return {"type": "object", "properties": {}}
    for name, p in sig.parameters.items():
        if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD) or name in ("self", "cls"):
            continue
        props[name] = {"type": _json_type(p.annotation)}
        if p.default is inspect.Parameter.empty:
            required.append(name)
    schema = {"type": "object", "properties": props}
    if required:
        schema["required"] = required
    return schema


def _tools_list():
    return [{"name": n, "description": d, "inputSchema": _schema(f)} for n, (f, d) in TOOLS.items()]


def _ok(id_, result):
    return json.dumps({"jsonrpc": "2.0", "id": id_, "result": result})


def _err(id_, code, msg):
    return json.dumps({"jsonrpc": "2.0", "id": id_, "error": {"code": code, "message": msg}})


def handle(req):
    id_ = req.get("id")
    method = req.get("method")
    if method == "initialize":
        return _ok(id_, {"protocolVersion": "2024-11-05", "capabilities": {"tools": {}},
                         "serverInfo": {"name": "sylva-functions", "version": "1"}})
    if method in ("notifications/initialized", "initialized"):
        return None
    if method == "tools/list":
        return _ok(id_, {"tools": _tools_list()})
    if method == "tools/call":
        params = req.get("params") or {}
        entry = TOOLS.get(params.get("name"))
        if entry is None:
            return _err(id_, -32601, "Unknown tool: %s" % params.get("name"))
        try:
            result = entry[0](**(params.get("arguments") or {}))
            return _ok(id_, {"content": [{"type": "text", "text": json.dumps(result, default=str)}],
                             "isError": False})
        except Exception as e:  # tool errors are reported, not fatal
            return _ok(id_, {"content": [{"type": "text", "text": "%s: %s" % (type(e).__name__, e)}],
                             "isError": True})
    return _err(id_, -32601, "Method not found: %s" % method)


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
        except json.JSONDecodeError:
            sys.stdout.write(_err(None, -32700, "Parse error") + "\\n")
            sys.stdout.flush()
            continue
        resp = handle(req)
        if resp is not None:
            sys.stdout.write(resp + "\\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
'''


def generate_server(db_path, root, allowlist):
    """Generate the standalone MCP server source. Returns `(code, tool_count,
    warnings)`. Raises FileNotFoundError if the database does not exist."""
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"database not found: {db_path}")

    targets, warnings = _resolve(db_path, root, allowlist)

    # Dedup by (module, fn); assign unique tool names (qualify on collision).
    seen, used = set(), set()
    tools = []  # (tool_name, module, fn, alias, desc)
    for module, fn, desc in targets:
        if (module, fn) in seen:
            continue
        seen.add((module, fn))
        name = fn if fn not in used else module.replace(".", "_") + "__" + fn
        used.add(name)
        tools.append((name, module, fn, "_sylva_" + name, desc))

    imports = "\n".join(f"from {m} import {fn} as {alias}" for (_, m, fn, alias, _) in tools)
    registrations = "\n".join(f"    {name!r}: ({alias}, {desc!r})," for (name, _, _, alias, desc) in tools)
    surface = "\n".join(f"  - {m}.{fn}  ->  tool '{name}'" for (name, m, fn, _, _) in tools)

    code = (
        _SERVER_TEMPLATE.replace("__SYLVA_SURFACE__", surface or "  (none — empty allowlist)")
        .replace("__SYLVA_ROOT__", repr(os.path.abspath(root)))
        .replace("__SYLVA_IMPORTS__", imports or "# (no functions exposed)")
        .replace("__SYLVA_REGISTRATIONS__", registrations)
    )
    return code, len(tools), warnings
