"""Feature 10.1 — deterministic project-brief (instruction-set) generation.

`generate_brief(db)` assembles an `AGENTS.md`-style markdown brief *mechanically*
from Sylva's code graph — archetype + layers (9.8), inferred entrypoints (9.1),
main spine (9.2), hubs + centrality (4.3/9.3), module map (4.6/4.7), and foreign
boundaries (5.0). It is the distilled "how this system works" a fresh agent
session can read instead of re-deriving the structure every time.

Deterministic and reproducible (same graph → same brief): Sylva stays mechanical
and never runs an LLM here; the optional skill wrapper (see `skills/`) invokes
this and lets an agent enrich the prose afterwards.
"""

import os
import sqlite3
from collections import defaultdict

import sylva


def _project_name(paths):
    if not paths:
        return "Project"
    try:
        common = os.path.commonpath(paths) if len(paths) > 1 else os.path.dirname(paths[0])
    except ValueError:  # mixed absolute/relative
        common = os.path.dirname(paths[0])
    return os.path.basename(common.rstrip("/\\")) or "Project"


def _is_test_file(path):
    """Whether `path` is test code — excluded from the brief so it reflects the
    real system, not the test suite (`test_*.py` / `*_test.py`, or a `tests/`
    directory)."""
    p = path.replace("\\", "/")
    base = p.rsplit("/", 1)[-1]
    if base.startswith("test_") or base.endswith("_test.py"):
        return True
    parts = p.split("/")
    return "tests" in parts or "test" in parts


def _db_facts(db_path):
    """Cheap counts/names read directly (no analysis)."""
    conn = sqlite3.connect(db_path)
    try:
        paths = [r[0] for r in conn.execute("SELECT path FROM files")]
        nsym = conn.execute(
            "SELECT COUNT(*) FROM symbols WHERE kind IN ('function', 'class')"
        ).fetchone()[0]
        foreign_mods = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM symbols WHERE kind = 'foreign_module' ORDER BY name"
            )
        ]
        foreign_exports = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM symbols WHERE kind = 'foreign_export' ORDER BY name"
            )
        ]
    finally:
        conn.close()
    return paths, nsym, foreign_mods, foreign_exports


def generate_brief(db_path):
    """Return a deterministic markdown project brief for the graph at `db_path`.

    Raises FileNotFoundError if the database does not exist.
    """
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"database not found: {db_path}")

    paths, nsym, fmods, fexports = _db_facts(db_path)
    name = _project_name(paths)

    layers = sylva.infer_layers(db_path)
    spine = sylva.main_spine(db_path)
    # Filter test code so the brief describes the system, not the test suite.
    eps = [e for e in sylva.infer_entrypoints(db_path) if not _is_test_file(e["file"])]
    cent = [c for c in sylva.centrality(db_path) if not _is_test_file(c["file"])]
    arch = sylva.get_architecture(db_path)
    hubs_all = [h for h in arch.get("hubs", []) if not _is_test_file(h.get("file", ""))]
    mods_all = [m for m in arch.get("modules", []) if not _is_test_file(m["path"])]
    layer_items = [e for e in layers["layers"] if not _is_test_file(e["file"])]
    primary = next((e for e in eps if e.get("primary")), None)
    n_src_files = len([p for p in paths if not _is_test_file(p)])
    n_src_syms = len(layer_items)

    out = []
    out.append(f"# {name} — Project Brief")
    out.append("")
    out.append(
        "> Auto-generated by Sylva from the code graph (deterministic — regenerate "
        "with `sylva brief`). A distilled map of how this system is structured."
    )
    out.append("")

    # --- Overview ---
    out.append("## Overview")
    out.append(f"- **Archetype:** {layers['archetype']}")
    out.append(
        f"- **Size:** {n_src_syms} functions/classes across {n_src_files} "
        f"source file(s) (tests excluded)"
    )
    if fmods or fexports:
        mods = ", ".join(f"`{m}`" for m in fmods) or "—"
        out.append(
            f"- **Foreign (black-box) modules:** {mods} "
            f"({len(fexports)} exported entrypoint(s) callable from Python)"
        )
    out.append("")

    # --- Entrypoints ---
    out.append("## Entrypoints")
    if primary:
        mk = f" ({primary['marker_kind']})" if primary.get("marker_kind") else ""
        out.append(
            f"- **Primary:** `{primary['symbol']}`{mk} — {primary['file']}:"
            f"{primary.get('line')} — reaches {primary.get('reachable')} symbol(s)"
        )
    for e in [e for e in eps if not e.get("primary")][:8]:
        mk = f" ({e['marker_kind']})" if e.get("marker_kind") else ""
        out.append(f"- `{e['symbol']}`{mk} — {e['file']}")
    if not eps:
        out.append("- (none inferred)")
    out.append("")

    # --- Main flow (spine) ---
    if spine.get("nodes"):
        chain = " → ".join(
            f"`{n['symbol']}`" for n in sorted(spine["nodes"], key=lambda n: n["layer"])
        )
        out.append("## Main flow (spine)")
        out.append(f"From `{spine['entry']}`: {chain}")
        out.append("")

    # --- Architectural layers (9.8) ---
    by_layer = defaultdict(set)
    for e in layer_items:
        by_layer[e["layer"]].add(e["symbol"])
    if layers["archetype"] != "library" and any(k != "business" for k in by_layer):
        out.append("## Architectural layers")
        for lay in ("interface", "transport", "business", "data"):
            syms = by_layer.get(lay)
            if syms:
                sample = ", ".join(f"`{s}`" for s in sorted(syms)[:8])
                more = "" if len(syms) <= 8 else f" (+{len(syms) - 8} more)"
                out.append(f"- **{lay}** ({len(syms)}): {sample}{more}")
        out.append("")

    # --- Key modules ---
    mods_sorted = sorted(mods_all, key=lambda m: -m["symbols"])[:8]
    if mods_sorted:
        out.append("## Key modules")
        for m in mods_sorted:
            out.append(f"- `{m['path']}` — {m['symbols']} symbol(s)")
        out.append("")

    # --- Key symbols (hubs / chokepoints / gateways) ---
    hubs = hubs_all[:6]
    if hubs:
        out.append("## Key symbols")
        out.append(
            "- **Hubs (most connected):** " + ", ".join(f"`{h['name']}`" for h in hubs)
        )
        chokes = [c for c in cent if c["betweenness"] > 0][:5]
        if chokes:
            out.append(
                "- **Chokepoints (betweenness):** "
                + ", ".join(f"`{c['symbol']}`" for c in chokes)
            )
        gates = [g for g in sorted(cent, key=lambda c: -c["dominates"]) if g["dominates"] > 0][:5]
        if gates:
            out.append(
                "- **Gateways (dominators):** "
                + ", ".join(f"`{g['symbol']}` ({g['dominates']})" for g in gates)
            )
        out.append("")

    # --- How to run ---
    run = [e for e in eps if e.get("marker_kind") in ("console_script", "cli", "main", "main_guard")]
    out.append("## How to run")
    if run:
        for e in run[:5]:
            out.append(f"- `{e['symbol']}` ({e['marker_kind']}) — {e['file']}")
    else:
        out.append("- No run entrypoint detected — likely a library (import and use its API).")
    out.append("")

    out.append("---")
    out.append(
        "_Generated by Sylva. Re-run `sylva brief` after re-indexing to refresh._"
    )
    out.append("")
    return "\n".join(out)
