"""Feature 10.1 — deterministic project-brief (instruction-set) generation.

`generate_brief(db)` assembles an `AGENTS.md`-style markdown brief *mechanically*
from Sylva's code graph — archetype + layers (9.8), inferred entrypoints (9.1),
main spine (9.2), hubs + centrality (4.3/9.3), module map (4.6/4.7), and foreign
boundaries (5.0). It is the distilled "how this system works" a fresh agent
session can read instead of re-deriving the structure every time.

Deterministic and reproducible (same graph → same brief): Sylva stays mechanical
and never runs an LLM here; the optional skill wrapper (see `skills/`) invokes
this and lets an agent enrich the prose afterwards.
"""

import os
import sqlite3
from collections import defaultdict

import sylva


def _project_name(paths):
    if not paths:
        return "Project"
    try:
        common = os.path.commonpath(paths) if len(paths) > 1 else os.path.dirname(paths[0])
    except ValueError:  # mixed absolute/relative
        common = os.path.dirname(paths[0])
    return os.path.basename(common.rstrip("/\\")) or "Project"


def _is_test_file(path):
    """Whether `path` is test code — excluded from the brief so it reflects the
    real system, not the test suite (`test_*.py` / `*_test.py`, or a `tests/`
    directory)."""
    p = path.replace("\\", "/")
    base = p.rsplit("/", 1)[-1]
    if base.startswith("test_") or base.endswith("_test.py"):
        return True
    parts = p.split("/")
    return "tests" in parts or "test" in parts


def _db_facts(db_path):
    """Cheap counts/names read directly (no analysis)."""
    conn = sqlite3.connect(db_path)
    try:
        paths = [r[0] for r in conn.execute("SELECT path FROM files")]
        nsym = conn.execute(
            "SELECT COUNT(*) FROM symbols WHERE kind IN ('function', 'class')"
        ).fetchone()[0]
        foreign_mods = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM symbols WHERE kind = 'foreign_module' ORDER BY name"
            )
        ]
        foreign_exports = [
            r[0]
            for r in conn.execute(
                "SELECT name FROM symbols WHERE kind = 'foreign_export' ORDER BY name"
            )
        ]
    finally:
        conn.close()
    return paths, nsym, foreign_mods, foreign_exports


def generate_brief(db_path):
    """Return a deterministic markdown project brief for the graph at `db_path`.

    Raises FileNotFoundError if the database does not exist.
    """
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"database not found: {db_path}")

    paths, nsym, fmods, fexports = _db_facts(db_path)
    name = _project_name(paths)

    layers = sylva.infer_layers(db_path)
    spine = sylva.main_spine(db_path)
    # Filter test code so the brief describes the system, not the test suite.
    eps = [e for e in sylva.infer_entrypoints(db_path) if not _is_test_file(e["file"])]
    cent = [c for c in sylva.centrality(db_path) if not _is_test_file(c["file"])]
    arch = sylva.get_architecture(db_path)
    hubs_all = [h for h in arch.get("hubs", []) if not _is_test_file(h.get("file", ""))]
    mods_all = [m for m in arch.get("modules", []) if not _is_test_file(m["path"])]
    layer_items = [e for e in layers["layers"] if not _is_test_file(e["file"])]
    primary = next((e for e in eps if e.get("primary")), None)
    n_src_files = len([p for p in paths if not _is_test_file(p)])
    n_src_syms = len(layer_items)

    out = []
    out.append(f"# {name} — Project Brief")
    out.append("")
    out.append(
        "> Auto-generated by Sylva from the code graph (deterministic — regenerate "
        "with `sylva brief`). A distilled map of how this system is structured."
    )
    out.append("")

    # --- Overview ---
    out.append("## Overview")
    out.append(f"- **Archetype:** {layers['archetype']}")
    out.append(
        f"- **Size:** {n_src_syms} functions/classes across {n_src_files} "
        f"source file(s) (tests excluded)"
    )
    if fmods or fexports:
        mods = ", ".join(f"`{m}`" for m in fmods) or "—"
        out.append(
            f"- **Foreign (black-box) modules:** {mods} "
            f"({len(fexports)} exported entrypoint(s) callable from Python)"
        )
    out.append("")

    # --- Entrypoints ---
    out.append("## Entrypoints")
    if primary:
        mk = f" ({primary['marker_kind']})" if primary.get("marker_kind") else ""
        out.append(
            f"- **Primary:** `{primary['symbol']}`{mk} — {primary['file']}:"
            f"{primary.get('line')} — reaches {primary.get('reachable')} symbol(s)"
        )
    for e in [e for e in eps if not e.get("primary")][:8]:
        mk = f" ({e['marker_kind']})" if e.get("marker_kind") else ""
        out.append(f"- `{e['symbol']}`{mk} — {e['file']}")
    if not eps:
        out.append("- (none inferred)")
    out.append("")

    # --- Main flow (spine) ---
    if spine.get("nodes"):
        chain = " → ".join(
            f"`{n['symbol']}`" for n in sorted(spine["nodes"], key=lambda n: n["layer"])
        )
        out.append("## Main flow (spine)")
        out.append(f"From `{spine['entry']}`: {chain}")
        out.append("")

    # --- Architectural layers (9.8) ---
    by_layer = defaultdict(set)
    for e in layer_items:
        by_layer[e["layer"]].add(e["symbol"])
    if layers["archetype"] != "library" and any(k != "business" for k in by_layer):
        out.append("## Architectural layers")
        for lay in ("interface", "transport", "business", "data"):
            syms = by_layer.get(lay)
            if syms:
                sample = ", ".join(f"`{s}`" for s in sorted(syms)[:8])
                more = "" if len(syms) <= 8 else f" (+{len(syms) - 8} more)"
                out.append(f"- **{lay}** ({len(syms)}): {sample}{more}")
        out.append("")

    # --- Key modules ---
    mods_sorted = sorted(mods_all, key=lambda m: -m["symbols"])[:8]
    if mods_sorted:
        out.append("## Key modules")
        for m in mods_sorted:
            out.append(f"- `{m['path']}` — {m['symbols']} symbol(s)")
        out.append("")

    # --- Key symbols (hubs / chokepoints / gateways) ---
    hubs = hubs_all[:6]
    if hubs:
        out.append("## Key symbols")
        out.append(
            "- **Hubs (most connected):** " + ", ".join(f"`{h['name']}`" for h in hubs)
        )
        chokes = [c for c in cent if c["betweenness"] > 0][:5]
        if chokes:
            out.append(
                "- **Chokepoints (betweenness):** "
                + ", ".join(f"`{c['symbol']}`" for c in chokes)
            )
        gates = [g for g in sorted(cent, key=lambda c: -c["dominates"]) if g["dominates"] > 0][:5]
        if gates:
            out.append(
                "- **Gateways (dominators):** "
                + ", ".join(f"`{g['symbol']}` ({g['dominates']})" for g in gates)
            )
        out.append("")

    # --- How to run ---
    run = [e for e in eps if e.get("marker_kind") in ("console_script", "cli", "main", "main_guard")]
    out.append("## How to run")
    if run:
        for e in run[:5]:
            out.append(f"- `{e['symbol']}` ({e['marker_kind']}) — {e['file']}")
    else:
        out.append("- No run entrypoint detected — likely a library (import and use its API).")
    out.append("")

    # --- For agents: navigate with Sylva, don't read files ---
    out.append("## Exploring this repo with an agent")
    out.append(
        "This codebase is exposed as a Sylva knowledge graph (MCP). **Navigate the "
        "graph instead of opening whole files** — it's exact and token-cheap:"
    )
    out.append("")
    out.append("- `get_overview` — orient (this brief, in one call)")
    out.append("- `list_symbols` / `get_outline <file>` — what exists · a file's skeleton (no bodies)")
    out.append("- `neighborhood` / `trace_calls` / `blast_radius` — how symbols connect")
    out.append("- `get_source <name>` — read only the function you need")
    out.append("")

    out.append("---")
    out.append(
        "_Generated by Sylva. Re-run `sylva brief` after re-indexing to refresh._"
    )
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Feature 8.1 — Detailed analysis report (health/risk metrics)                 #
# --------------------------------------------------------------------------- #

_TOP_HUBS_FOR_RISK = 5  # blast radius is computed for the N most-connected hubs


def _coverage_and_gaps(db_path):
    """Read coverage buckets + orphan symbols straight from the graph.

    Returns `(has_any_coverage, uncovered, never_measured, orphans)`, each a
    sorted list of `{name, file, line}` (except the bool). All test code is
    excluded so the report reflects the real system, not its test suite.
    """
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT s.name, f.path, s.line_start, s.coverage_pct, "
            "       (s.id IN (SELECT src_id FROM edges) "
            "        OR s.id IN (SELECT dst_id FROM edges)) AS connected "
            "FROM symbols s JOIN files f ON s.file_id = f.id "
            "WHERE s.kind IN ('function', 'class')"
        ).fetchall()
    finally:
        conn.close()

    has_any = False
    uncovered, never_measured, orphans = [], [], []
    for name, path, line, cov, connected in rows:
        if _is_test_file(path):
            continue
        item = {"name": name, "file": path, "line": line}
        if cov is None:
            never_measured.append(item)
        else:
            has_any = True
            if cov == 0.0:
                uncovered.append(item)
        if not connected:
            orphans.append(item)

    key = lambda d: (d["file"], d["line"] if d["line"] is not None else 0, d["name"])
    return (
        has_any,
        sorted(uncovered, key=key),
        sorted(never_measured, key=key),
        sorted(orphans, key=key),
    )


def report_data(db_path):
    """Assemble the machine-readable report structure (the `report.json` shape).

    Deterministic: same graph → identical data. Raises FileNotFoundError if the
    database does not exist. Each section is gathered defensively — a query that
    fails degrades to an empty/flagged section rather than aborting the report.
    """
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"database not found: {db_path}")

    paths, nsym, _fmods, _fexports = _db_facts(db_path)
    name = _project_name(paths)
    n_src_files = len([p for p in paths if not _is_test_file(p)])

    def _safe(fn, default):
        try:
            return fn()
        except Exception as exc:  # a failing section is a noted gap, never fatal
            _safe.errors.append(str(exc))
            return default

    _safe.errors = []

    # --- Architecture (4.3) ---
    arch = _safe(lambda: sylva.get_architecture(db_path), {})
    modules = sorted(
        (m for m in arch.get("modules", []) if not _is_test_file(m["path"])),
        key=lambda m: (-m["symbols"], m["path"]),
    )
    hubs = [h for h in arch.get("hubs", []) if not _is_test_file(h.get("file", ""))]
    entry_points = [
        e for e in arch.get("entry_points", []) if not _is_test_file(e.get("file", ""))
    ]

    # --- Coverage (3.4) + gaps ---
    module_cov_raw = _safe(lambda: sylva.get_module_coverage(db_path), {})
    module_cov = sorted(
        (
            {"module": mod, "coverage": pct}
            for mod, pct in module_cov_raw.items()
            if not _is_test_file(mod)
        ),
        key=lambda d: (d["module"],),
    )
    has_cov, uncovered, never_measured, orphans = _safe(
        lambda: _coverage_and_gaps(db_path), (False, [], [], [])
    )

    # --- Risk: blast radius of the top hubs (4.2) ---
    risk = []
    for h in hubs[:_TOP_HUBS_FOR_RISK]:
        affected = _safe(lambda h=h: sylva.blast_radius(db_path, h["name"]), [])
        risk.append(
            {
                "symbol": h["name"],
                "file": h.get("file", ""),
                "affected": len(affected),
            }
        )
    risk.sort(key=lambda r: (-r["affected"], r["symbol"]))

    return {
        "project": name,
        "symbols": nsym,
        "source_files": n_src_files,
        "architecture": {
            "modules": modules,
            "hubs": hubs,
            "entry_points": entry_points,
        },
        "coverage": {
            "measured": has_cov,
            "modules": module_cov,
            "uncovered": uncovered,
            "never_measured": never_measured,
        },
        "risk": risk,
        "gaps": {"orphans": orphans},
        "errors": _safe.errors,
    }


def _fmt_list(items, empty="_none_"):
    return ", ".join(f"`{i}`" for i in items) if items else empty


def generate_report(db_path):
    """Return a deterministic markdown health/risk report for `db_path`.

    The metrics counterpart to `generate_brief`: architecture, coverage gaps,
    change-risk (blast radius), and structural gaps (orphans). Raises
    FileNotFoundError if the database does not exist.
    """
    d = report_data(db_path)
    out = []
    out.append(f"# {d['project']} — Analysis Report")
    out.append("")
    out.append(
        "> Auto-generated by Sylva from the code graph (deterministic — regenerate "
        "with `sylva report`). Health & risk metrics for this codebase."
    )
    out.append("")
    out.append(
        f"- **Symbols:** {d['symbols']} function(s)/class(es) across "
        f"{d['source_files']} source file(s) (tests excluded)"
    )
    out.append("")

    # --- Architecture ---
    arch = d["architecture"]
    out.append("## Architecture")
    if arch["modules"]:
        out.append("")
        out.append("| Module | Symbols |")
        out.append("| --- | ---: |")
        for m in arch["modules"][:15]:
            out.append(f"| `{m['path']}` | {m['symbols']} |")
    else:
        out.append("- _no modules indexed_")
    out.append("")
    out.append(
        "- **Top hubs (by degree):** "
        + _fmt_list(f"{h['name']} ({h['degree']})" for h in arch["hubs"][:8])
    )
    out.append(
        "- **Entry points:** "
        + _fmt_list(e["name"] for e in arch["entry_points"][:8])
    )
    out.append("")

    # --- Coverage ---
    cov = d["coverage"]
    out.append("## Coverage")
    if not cov["measured"]:
        out.append(
            "- No coverage data in the graph. Run coverage and `apply_coverage` "
            "to populate it (see Epic 3)."
        )
    else:
        out.append("")
        out.append("| Module | Coverage |")
        out.append("| --- | ---: |")
        for m in cov["modules"]:
            out.append(f"| `{m['module']}` | {m['coverage']:.0f}% |")
        out.append("")
        un = cov["uncovered"]
        out.append(
            f"- **Uncovered (0%) symbols ({len(un)}):** "
            + _fmt_list(i["name"] for i in un[:20])
            + (f" _(+{len(un) - 20} more)_" if len(un) > 20 else "")
        )
    nm = cov["never_measured"]
    out.append(
        f"- **Never-measured symbols ({len(nm)}):** "
        + _fmt_list(i["name"] for i in nm[:20])
        + (f" _(+{len(nm) - 20} more)_" if len(nm) > 20 else "")
    )
    out.append("")

    # --- Risk ---
    out.append("## Risk (change blast radius)")
    if d["risk"]:
        for r in d["risk"]:
            out.append(
                f"- Changing `{r['symbol']}` affects **{r['affected']}** symbol(s)"
            )
    else:
        out.append("- _no hubs to assess (no call/import edges)_")
    out.append("")

    # --- Gaps ---
    orphans = d["gaps"]["orphans"]
    out.append("## Gaps")
    out.append(
        f"- **Orphan symbols — no inbound/outbound edges ({len(orphans)}):** "
        + _fmt_list(i["name"] for i in orphans[:20])
        + (f" _(+{len(orphans) - 20} more)_" if len(orphans) > 20 else "")
    )
    out.append(
        "- _Parse errors and unresolved/ambiguous references are not persisted "
        "in the graph; run indexing with `SYLVA_LOG` for edge-resolution "
        "diagnostics._"
    )
    if d["errors"]:
        out.append(
            f"- **Report warnings:** {len(d['errors'])} section(s) degraded — "
            + _fmt_list(d["errors"])
        )
    out.append("")

    out.append("---")
    out.append("_Generated by Sylva. Re-run `sylva report` after re-indexing._")
    out.append("")
    return "\n".join(out)
